custom:
  http:
    port: ${httpPort:8080}

vaadin:
  servlet:
    productionMode: true
    heartbeatInterval: 60
    closeIdleSessions: true

server:
  port: ${httpsPort:8443}
  ssl:
    key-store: classpath:keystore/localhost.p12
    key-store-password: aliozan
    keyStoreType: PKCS12
    keyAlias: local
  undertow:
    accesslog:
      dir: /workspace-link/logs/vaadin-book-store/
      enabled: true

logging:
  file: /workspace-link/logs/vaadin-book-store/vaadin-app.log
  level:
    root: INFO
    org.springframework: ERROR
    org.hibernate: ERROR
    com.zaxxer: ERROR
    com.vaadin: WARN

spring:
  h2:
    console:
      enabled: false
  datasource:
    # in memory
    url: jdbc:h2:mem:appdb
    # persisted
    # url: jdbc:h2:file:/workspace-link/h2-db
    username: ozan
    password:
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: hikari-h2-db-pool
      maximum-pool-size: 5
      connection-timeout: 30000